all: false
recursive: false
dir: '{{.InterfaceDir}}'
filename: mocks_test.go
force-file-write: false
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
template: testify
packages:
  game-server-golang/internal/gateway:
    config:
      recursive: true
      all: true
  game-server-golang/internal/usecase:
    config:
      recursive: true
      all: true
