all: false
recursive: false
force-file-write: true
formatter: goimports
template: testify
dir: "./internal/test/mocks"
filename: "mocks_{{.SrcPackageName}}.go"
pkgname: "mocks"
structname: "Mock{{.InterfaceName}}"
packages:
  game-server-golang/internal/gateway:
    config:
      recursive: true
      all: true
  game-server-golang/internal/usecase:
    config:
      recursive: true
      all: true
