all: false
recursive: false
force-file-write: true
formatter: goimports
template: testify
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
pkgname: "{{.SrcPackageName}}_test"
structname: "Mock{{.InterfaceName}}"
packages:
  game-server-golang/internal/gateway:
    config:
      recursive: true
      all: true
  game-server-golang/internal/usecase:
    config:
      recursive: true
      all: true
