.DEFAULT_GOAL := help

# Help command code generated by AI
help: ## Show this help message
	@echo "Available commands:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

db-migrate: ## Runs the database migration
	@echo "Migrating database"
	@go run tools/sql_lite_migration.go

run: ## Run the server
	@echo "Running server"
	@go run main.go

lint:
	@docker run --rm -v $(pwd) -w /app golangci/golangci-lint:v2.5.0 golangci-lint run