.DEFAULT_GOAL := help


BIN_DIR :=  $(shell pwd)/bin
GOLANGCI_LINT := $(BIN_DIR)/golangci-lint
GOLANGCI_LINT_VERSION := v2.5.0

# Help command code generated by AI
help: ## Show this help message
	@echo "Available commands:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

db-migrate: ## Runs the database migration
	@echo "Migrating database"
	@go run tools/sql_lite_migration.go

run: ## Run the server
	@echo "Running server"
	@go run main.go

$(GOLANGCI_LINT):
	@echo "Instalando golangci-lint em $(BIN_DIR)..."
	@mkdir -p $(BIN_DIR)
	@curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
		| sh -s -- -b $(BIN_DIR) $(GOLANGCI_LINT_VERSION)

.PHONY: lint
lint: $(GOLANGCI_LINT) ## Roda linter
	@$(GOLANGCI_LINT) run ./...