# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"
  timeoutinseconds: 5

# Database Configuration
database:
  name: "local.db"
  host: "localhost"
  port: 5432
  username: ""  # Not needed for SQLite
  password: ""  # Not needed for SQLite

# Logging Configuration
logging:
  level: "info"      # Available: debug, info, warn, error
  format: "json"     # Available: json, console
  disablecaller: false  # Adds file:line to log entries